language: ruby

rvm: 2.6.5

branches:
  only:
  - master

bundler_args: --jobs=3 --retry=3

env:
  - RAILS=4.2
  - RAILS=5.0
  - RAILS=5.1
  - RAILS=5.2
  - RAILS=6.0

script:
  - bundle exec rubocop
  - bundle exec rspec
