require: rubocop-rspec
inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/SpecFilePathFormat:
  Exclude:
    - ja2r_spec.rb
    - ja2r/**

Style/BlockDelimiters:
  Enabled: false
