name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rails: ['4.2', '5.0', '5.1', '5.2', '6.0']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle
      env:
        RAILS: ${{ matrix.rails }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Rspec
      run: bundle exec rspec
    - name: Rubocop
      run: bundle exec rubocop
